### ISSUE TITLE
Yearly not showing up

### ISSUE THREAD

**Issue by tts** [karthik/almviz#1]
With JSON returned from this API call http://alm.plos.org/api/v3/articles?api_key=[my key]&ids=10.1371%2Fjournal.pone.0024408&info=history I can produce http://users.tkk.fi/~sonkkila/almviz/almviz-master/ which shows nicely a monthly stat with bars changing color by year - but I expected to see a 'yearly' sum option too. Am I missing something here?

**Comment by jalperin** [comment]
This repo is no longer maintained. Please try the latest code at in [my github repo](https://github.com/jalperin/almviz). The reason you're not seeing yearly, however, is that there is a minimum number of events necessary before year's show up. You can configure this by setting "minYearsForYearly" to something lower than 6.

**Comment by tts** [comment]
Thanks for both!
